---
# See https://github.com/jvautier/project-cli
fullname: jvautier/docker-compose-taiga
description: Docker-compose development stack with taiga.
tags:
  - development
  - docker
  - docker-compose
  - taiga
github: {}
